<a href="https://colab.research.google.com/github/LEESANGMIN79/-/blob/main/4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C3_1_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

shape = (3,3,6)

arr = np.random.randint(0,21,shape)

print(arr)

[[[ 8 13 13  2 12 12]
  [14 16  7 14 18  6]
  [15  5  4 13 17  3]]

 [[14 13 17  4 14  4]
  [19  5 11  7 12 11]
  [13  0 13  7 10 18]]

 [[10  3 18 17  8 11]
  [12 17  9  5  8  1]
  [ 1 17 18  1  4 14]]]
