<a href="https://colab.research.google.com/github/LEESANGMIN79/-/blob/main/4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

results = []

for _ in range(3):
    a = np.arange(1, 46)
    np.random.shuffle(a)
    lotto = a[:6]
    results.append(lotto)

results_array = np.array(results)
print(results_array)


[[28 24 29 38  5 42]
 [43  7 21 39 35  1]
 [42 38 12 33  8 28]]
