<a href="https://colab.research.google.com/github/LEESANGMIN79/-/blob/main/4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C3_2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

shape = (5,6)

arr = np.random.randint(0,101,shape)

print(arr)

[[51 34 54  2 79 46]
 [38 46 43 29  8 89]
 [46 17 48 16 78 72]
 [94 44 17  0 23 97]
 [54 54 80 75  4 65]]
